# Generated by Django 5.1.1 on 2025-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team', to='CRM.userprofile'),
        ),
    ]
