# Generated by Django 5.1.1 on 2025-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_salaryslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
